apiVersion: apps/v1
kind: Deployment
metadata:
    name: task-app-mongodb-deployment
    labels:
        app: task-app-mongodb
spec:
    replicas: 1
    selector:
        matchLabels:
            app: task-app-mongodb
    template:
        metadata:
            name: task-app-mongodb
            labels:
                app: task-app-mongodb
        spec:
            containers:
                - name: task-app-mongodb
                  image: mongo
                  ports:
                      - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
    name: task-app-mongodb-service
spec:
    selector:
        app: task-app-mongodb # should match with pod label
    ports:
        - protocol: TCP
          port: 27017 # can be any value
          targetPort: 27017 # should match with container port
