apiVersion: apps/v1
kind: Deployment
metadata:
    name: task-app-mongo-express-deployment
    labels:
        app: task-app-mongo-express
spec:
    replicas: 1
    selector:
        matchLabels:
            app: task-app-mongo-express
    template:
        metadata:
            name: task-app-mongo-express
            labels:
                app: task-app-mongo-express
        spec:
            containers:
                - name: task-app-mongo-express
                  image: mongo-express
                  ports:
                      - containerPort: 8081
                  env:
                      - name: ME_CONFIG_MONGODB_SERVER
                        valueFrom:
                            configMapKeyRef:
                                name: task-app-mongo-express-configmap
                                key: database_url
---
apiVersion: v1
kind: Service
metadata:
    name: task-app-mongo-express-service
spec:
    selector:
        app: task-app-mongo-express
    # type: NodePort
    ports:
        - protocol: TCP
          port: 8081
          targetPort: 8081
          # nodePort: 30000 #can be any port from 30000 - 32767
